@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhMDllN2M3LTdjYTYtNGY2Yi05YTRjLWNjNzZmNmJiNTM2MyIsImlhdCI6MTcyNTcyNjU2MSwic3ViIjoiZmEwOWU3YzctN2NhNi00ZjZiLTlhNGMtY2M3NmY2YmI1MzYzIn0.iyjCO03kZYQEWhqgj7BerYY2kRGqLmnermPTaFAcEj4


# @name buscar_todas_barbershops
GET http://localhost:3333/barbershops

###

# @name buscar__barbershop_por_id
GET http://localhost:3333/barbershops/f8c4bd54-75be-42c9-ab7b-469f113ab5ca

###

# @name cadastrar_barbershop

POST http://localhost:3333/barbershops
Content-Type: application/json

{
  "name": "HairSalon", 
  "email": "hair@salon.com", 
  "password": "123", 
  "contactName": "Pedro", 
  "contactPhone": "(11) 11111-1111"
}

###

# @name deletar_barbershop
DELETE http://localhost:3333/barbershops/5c27dfe8-69aa-47a6-a457-9c63705a6584

###

# @name update_barbershop
PUT http://localhost:3333/barbershops/f8c4bd54-75be-42c9-ab7b-469f113ab5c
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Barbershop Teste"
}

###

# @name logar
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "joao@barbearia.com", 
  "password": "123"
}

###

# @name register_booking_manually

POST http://localhost:3333/bookings
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2024-05-26T18:00:00.205Z",
  "serviceId": "82e1acbf-f46b-416e-a1a6-1799ac896dc8",
  "clientId": "1a7761e3-902e-44ba-9697-4e298f75bfc5",
  "professionalId": "af46da8a-2648-4ab4-87b6-53c586784261",
  "status": "PENDING"
}

###

# @name fetch_bookings_from_auth_barbershop

GET http://localhost:3333/bookings
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST http://localhost:3333/services
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Corte",
  "priceInCents": 3500,
  "description": "Corte",
  "durationInMinutes": 30
}

###

POST http://localhost:3333/professionals
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "João Barbeiro",
  "email": "joao@email.com",
  "phone": "(19) 12345-6789",
  "cpf": "123.456.789-01"
}

###

GET http://localhost:3333/professionals
Content-Type: application/json
Authorization: Bearer {{token}}

###

DELETE http://localhost:3333/professionals/bd30bb07-f924-4128-b41c-72700835a23b
Content-Type: application/json
Authorization: Bearer {{token}}

###

Get http://localhost:3333/clients
Content-Type: application/json
Authorization: Bearer {{token}}

###

POST http://localhost:3333/clients
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "João Cliente",
  "phone": "(19) 12345-6789"
}

###

GET http://localhost:3333/metrics?month=9&year=2024
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET http://localhost:3333/metrics/income-per-day?month=7&year=2024
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET http://localhost:3333/metrics/income-per-professional?month=9&year=2024
Content-Type: application/json
Authorization: Bearer {{token}}

###

GET http://localhost:3333/metrics/average-bookings-per-day-of-week?month=9&year=2024
Content-Type: application/json
Authorization: Bearer {{token}}


###

GET http://localhost:3333/payments
Content-Type: application/json
Authorization: Bearer {{token}}


###

POST http://localhost:3333/payments
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "date": "2024-08-22T10:30:00.000Z",
  "bookingId": "7a932855-fbd9-4691-8156-221b6cc42301",
  "method": "CARD"
}