@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI0OTg0MTJhLTk2NzMtNDNlMy1iY2EzLTBkNTk0MTI3NWJlOSIsImlhdCI6MTcxNTg3MzIxNX0.KZ5BAjpDfSFXzmbdbk9lsarsU03CtAJzLn5APxWVVWQ


# @name buscar_todas_barbershops
GET http://localhost:3333/barbershops

###

# @name buscar__barbershop_por_id
GET http://localhost:3333/barbershops/f8c4bd54-75be-42c9-ab7b-469f113ab5ca

###

# @name cadastrar_barbershop

POST http://localhost:3333/barbershops
Content-Type: application/json

{
  "name": "Breninho do corte", 
  "email": "breno@barbearia.com", 
  "password": "123", 
  "contactName": "Breno", 
  "contactPhone": "(11) 11111-1111"
}

###

# @name deletar_barbershop
DELETE http://localhost:3333/barbershops/5c27dfe8-69aa-47a6-a457-9c63705a6584

###

# @name update_barbershop
PUT http://localhost:3333/barbershops/f8c4bd54-75be-42c9-ab7b-469f113ab5c
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Barbershop Teste"
}

###

# @name logar
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "joao@email.com", 
  "password": "123"
}

###

